#publish-and-release.yml
name: Publish and release

on:
  release:
    types: [published]

jobs:

  publish-and-release:
    
    runs-on: windows-latest
    
    steps:
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: 8.0.x
    
    - name: Setup NuGet.exe
      uses: NuGet/setup-nuget@v2.0.0
      with:
        nuget-version: latest
      
    - name: Checkout repository
      uses: actions/checkout@v4.1.2
    
    - name: Set version
      run: . .\Setup\SetVersion.ps1; Set-Version -ReleaseTag $Env:GITHUB_REF_NAME
      shell: pwsh
    
    - name: Restore dependencies
      run: dotnet restore
      shell: pwsh
    
    - name: Build
      run: dotnet build --no-restore
      shell: pwsh
    
    - name: Test
      run: dotnet test --no-build --verbosity normal
      shell: pwsh
            
    - name: Publish (x86)
      run: dotnet publish .\FileExtractor\FileExtractor.csproj --configuration release --framework net8.0 --runtime win-x86 --no-self-contained
      shell: pwsh
    
    - name: Publish (x64)
      run: dotnet publish .\FileExtractor\FileExtractor.csproj --configuration release --framework net8.0 --runtime win-x64 --no-self-contained
      shell: pwsh
    
    - name: Download latest InnoSetup package
      run: nuget install Tools.InnoSetup -DependencyVersion Highest -Version 6.2.2
      shell: pwsh
    
    - name: Pack (x86)
      run: .\Tools.InnoSetup.6.2.2\tools\iscc.exe /Qp .\Setup\Setup_x86.iss
      shell: pwsh

    - name: Pack (x64)
      run: .\Tools.InnoSetup.6.2.2\tools\iscc.exe /Qp .\Setup\Setup_x64.iss
      shell: pwsh
      
    - name: Create Release
      uses: ncipollo/release-action@v1.14.0
      with:
        allowUpdates: true
        artifactErrorsFailBuild: true 
        artifacts: .\Output\FileExtractorSetup_x86.exe,.\Output\FileExtractorSetup_x64.exe
        artifactContentType: raw
        replacesArtifacts: true
        token: ${{ secrets.GITHUB_TOKEN }}
